import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Blog application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background flex flex-col font-sans antialiased",
          fontSans.variable
        )}
      >
        <Navbar />
        <div className="flex flex-col flex-1">
          <main className="flex-1">{children}</main>
        </div>

        <Footer />
      </body>
    </html>
  );
}
